# Generated by Django 4.0.3 on 2022-04-04 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='disliked_users',
            field=models.ManyToManyField(blank=True, related_name='dislikeds_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
