# Generated by Django 4.0.3 on 2022-04-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('tests', '0002_test_disliked_users_test_liked_users_test_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='tags.tag'),
        ),
    ]
