# Generated by Django 4.0.3 on 2022-04-04 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_solvedtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='tests.test'),
        ),
    ]
