# Generated by Django 4.0.3 on 2022-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_question_options_alter_test_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='solvedtest',
            old_name='answers',
            new_name='questions',
        ),
        migrations.AddField(
            model_name='test',
            name='blocking_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
