# Generated by Django 4.0.3 on 2022-04-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
