# Generated by Django 4.0.3 on 2022-04-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_alter_test_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solvedquestion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='solvedtest',
            options={'ordering': ['-date_ended']},
        ),
    ]
